title: Prince Ntimeni
logo: /Assests/Prince Siboniso Ntimeni- D.S (1).png
description: Versatile professional skilled in software development, data science, machine learning, and analytics, with expertise in high-performance applications, predictive modelling, and big data technologies.
#Azure , Machine learning , SQL, Python, Java, Terradata
#show_downloads: true
theme: jekyll-theme-minimal
