title: Prince Ntimeni
logo: /Assests/Prince Siboniso Ntimeni- D.S (1).png
description: versatile and results-driven professional with expertise in software development, data science, machine learning, data analytics, and quantitative analytics. Adept at designing and implementing
high-performance applications, developing advanced machine learning models, and deriving actionable
insights from complex datasets. Strong analytical mindset with experience in predictive modelling,
statistical analysis, and big data technologies.
#show_downloads: true
theme: jekyll-theme-minimal
